// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RestForMore.Api.Data;

#nullable disable

namespace RestForMore.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005121351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RestForMore.Api.Models.Mode", b =>
                {
                    b.Property<Guid>("ModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mode_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ModeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("mode_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ModeId");

                    b.HasIndex("UserId");

                    b.ToTable("modes", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.ModeBlockedApp", b =>
                {
                    b.Property<Guid>("ModeBlockedAppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("mode_blocked_app_id");

                    b.Property<string>("AppIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("app_identifier");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("app_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("mode_id");

                    b.HasKey("ModeBlockedAppId");

                    b.HasIndex("ModeId", "AppIdentifier")
                        .IsUnique();

                    b.ToTable("mode_blocked_apps", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.OnboardingProfile", b =>
                {
                    b.Property<Guid>("OnboardingProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("onboarding_profile_id");

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("age_group");

                    b.Property<string>("BiggestChallenge")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("biggest_challenge");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomActivity")
                        .HasColumnType("text")
                        .HasColumnName("custom_activity");

                    b.Property<string>("FeasibleStep")
                        .HasColumnType("text")
                        .HasColumnName("feasible_step");

                    b.Property<string>("MainGoal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("main_goal");

                    b.Property<int?>("OnboardingStep")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_step");

                    b.Property<int?>("PhoneFreeTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("phone_free_target_minutes");

                    b.Property<string>("PhoneUseInBed")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_use_in_bed");

                    b.Property<string>("PreferredActivity")
                        .HasColumnType("text")
                        .HasColumnName("preferred_activity");

                    b.Property<string>("ProductExpectation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("UNKNOWN")
                        .HasColumnName("product_expectation");

                    b.Property<string>("ProductIssue")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_issue");

                    b.Property<string>("ProductOwnership")
                        .HasColumnType("text")
                        .HasColumnName("product_ownership");

                    b.Property<TimeOnly?>("ReminderTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("reminder_time");

                    b.Property<string>("RestMoments")
                        .HasColumnType("text")
                        .HasColumnName("rest_moments");

                    b.Property<string>("Rhythm")
                        .HasColumnType("text")
                        .HasColumnName("rhythm");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("WantsSupport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("wants_support");

                    b.HasKey("OnboardingProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("onboarding_profiles", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.Program", b =>
                {
                    b.Property<Guid>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_day");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("ProgramId");

                    b.HasIndex("UserId");

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.ProgramDay", b =>
                {
                    b.Property<Guid>("ProgramDayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("program_day_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<DateTime?>("OfferedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("offered_at");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProgramDayId");

                    b.HasIndex("ProgramId", "DayNumber")
                        .IsUnique();

                    b.ToTable("program_days", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.Routine", b =>
                {
                    b.Property<Guid>("RoutineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("routine_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RoutineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("routine_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RoutineId");

                    b.HasIndex("UserId");

                    b.ToTable("routines", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.RoutineItem", b =>
                {
                    b.Property<Guid>("RoutineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("routine_item_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<Guid>("RoutineId")
                        .HasColumnType("uuid")
                        .HasColumnName("routine_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("RoutineItemId");

                    b.HasIndex("RoutineId");

                    b.ToTable("routine_items", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.Session", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("ModeId")
                        .HasColumnType("uuid")
                        .HasColumnName("mode_id");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<int>("PlannedDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("planned_duration_seconds");

                    b.Property<int?>("RemainingDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("remaining_duration_seconds");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SessionId");

                    b.HasIndex("ModeId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.SessionBlockedApp", b =>
                {
                    b.Property<Guid>("SessionBlockedAppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("session_blocked_app_id");

                    b.Property<string>("AppIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("app_identifier");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("app_name");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("SessionBlockedAppId");

                    b.HasIndex("SessionId", "AppIdentifier")
                        .IsUnique();

                    b.ToTable("session_blocked_apps", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("MarketingConsent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("marketing_consent");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("RestForMore.Api.Models.Mode", b =>
                {
                    b.HasOne("RestForMore.Api.Models.User", "User")
                        .WithMany("Modes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestForMore.Api.Models.ModeBlockedApp", b =>
                {
                    b.HasOne("RestForMore.Api.Models.Mode", "Mode")
                        .WithMany("BlockedApps")
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mode");
                });

            modelBuilder.Entity("RestForMore.Api.Models.OnboardingProfile", b =>
                {
                    b.HasOne("RestForMore.Api.Models.User", "User")
                        .WithOne("OnboardingProfile")
                        .HasForeignKey("RestForMore.Api.Models.OnboardingProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestForMore.Api.Models.Program", b =>
                {
                    b.HasOne("RestForMore.Api.Models.User", "User")
                        .WithMany("Programs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestForMore.Api.Models.ProgramDay", b =>
                {
                    b.HasOne("RestForMore.Api.Models.Program", "Program")
                        .WithMany("ProgramDays")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("RestForMore.Api.Models.Routine", b =>
                {
                    b.HasOne("RestForMore.Api.Models.User", "User")
                        .WithMany("Routines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RestForMore.Api.Models.RoutineItem", b =>
                {
                    b.HasOne("RestForMore.Api.Models.Routine", "Routine")
                        .WithMany("RoutineItems")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("RestForMore.Api.Models.Session", b =>
                {
                    b.HasOne("RestForMore.Api.Models.Mode", "Mode")
                        .WithMany("Sessions")
                        .HasForeignKey("ModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mode");
                });

            modelBuilder.Entity("RestForMore.Api.Models.SessionBlockedApp", b =>
                {
                    b.HasOne("RestForMore.Api.Models.Session", "Session")
                        .WithMany("BlockedApps")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RestForMore.Api.Models.Mode", b =>
                {
                    b.Navigation("BlockedApps");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RestForMore.Api.Models.Program", b =>
                {
                    b.Navigation("ProgramDays");
                });

            modelBuilder.Entity("RestForMore.Api.Models.Routine", b =>
                {
                    b.Navigation("RoutineItems");
                });

            modelBuilder.Entity("RestForMore.Api.Models.Session", b =>
                {
                    b.Navigation("BlockedApps");
                });

            modelBuilder.Entity("RestForMore.Api.Models.User", b =>
                {
                    b.Navigation("Modes");

                    b.Navigation("OnboardingProfile");

                    b.Navigation("Programs");

                    b.Navigation("Routines");
                });
#pragma warning restore 612, 618
        }
    }
}
